<?php
    
    namespace Protoqol\Prequel\App;
    
    use Carbon\Carbon;
    use Illuminate\Support\Facades\Artisan;
    use Protoqol\Prequel\Traits\classResolver;
    use Protoqol\Prequel\Database\DatabaseTraverser;
    use Protoqol\Prequel\Interfaces\GenerationInterface;
    
    class ModelAction implements GenerationInterface
    {
        
        use classResolver;
        
        /**
         * Generate
         *
         * @param string $database
         * @param string $table
         *
         * @return mixed
         */
        public function generate(string $database, string $table)
        {
            Artisan::call('make:model', [
                'name' => $this->generateModelName($table),
            ]);
            
            $this->setActualTable($table, (bool)($this->configNamespaceResolver('model')->suffix === ''));
            
            $this->dumpAutoload();
            
            return (string)$this->getName($database, $table);
        }
        
        /**
         * Get class name, when possible with namespace
         *
         * @param string $database
         * @param string $table
         *
         * @return mixed
         */
        public function getName(string $database, string $table)
        {
            return (new DatabaseTraverser())->getModel($table)['namespace'] ?? false;
        }
        
        /**
         * If user has set a suffix for their models this method will add a protected $table attribute to their model.
         * This will also a timestamp and Prequel signature at the top of every model generated by Prequel.
         *
         * @param string $table
         * @param bool   $onlyMark
         *
         * @return bool|int
         */
        public function setActualTable(string $table, bool $onlyMark = false)
        {
            // Get path for Model
            $path    = base_path('app/' . $this->generateModelName($table) . '.php');
            $path    = preg_replace("~[\\\/]~", DIRECTORY_SEPARATOR, $path);
            $content = file_get_contents($path);
            
            if ($onlyMark) {
                // Replacement attribute, kindly do not touch! :)
                $comment     = "// Better model organisation and an automatic \$table attribute setter, this saved you at least 2 seconds! - Prequel";
                $replacement = $comment . "\n    protected \$table = '" . $table . "';";
                
                // Replace the double slashes (//) in the newly created model with an attribute for the actual table name.
                $content = preg_replace('@//@', $replacement, $content);
            }
            
            // Stamp
            $stamp   = "<?php\n\n// Generated by Prequel @" . (string)Carbon::now();
            $content = preg_replace('@<\?php@', $stamp, $content);
            
            return file_put_contents($path, $content);
        }
        
        /**
         * STUB
         */
        public function setActualConnection()
        {
            // STUB
        }
    }
